<?php
namespace app\models;

class FileTypesIcons{



    public static function getIcon($type){
        $fileTypesIcon = array (
            '/img/icon-files/AC3.png' => 'ac3',
            '/img/icon-files/ACE.png' => 'ace',
            '/img/icon-files/ADE.png' => 'ade',
            '/img/icon-files/ADP.png' => 'adp',
            '/img/icon-files/AI.png' => 'ai',
            '/img/icon-files/AIFF.png' => 'aiff',
            '/img/icon-files/AU.png' => 'au',
            '/img/icon-files/AVI.png' => 'avi',
            '/img/icon-files/BAT.png' => 'bat',
            '/img/icon-files/BIN.png' => 'bin',
            '/img/icon-files/BMP.png' => 'bmp',
            '/img/icon-files/BUP.png' => 'bup',
            '/img/icon-files/CAB.png' => 'cab',
            '/img/icon-files/CAT.png' => 'cat',
            '/img/icon-files/CHM.png' => 'chm',
            '/img/icon-files/CSS.png' => 'css',
            '/img/icon-files/CUE.png' => 'cue',
            '/img/icon-files/DAT.png' => 'dat',
            '/img/icon-files/DCR.png' => 'dcr',
            '/img/icon-files/Default.png' => 'default',
            '/img/icon-files/DER.png' => 'der',
            '/img/icon-files/DIC.png' => 'dic',
            '/img/icon-files/DIVX.png' => 'divx',
            '/img/icon-files/DIZ.png' => 'diz',
            '/img/icon-files/DLL.png' => 'dll',
            '/img/icon-files/DOC.png' => 'doc',
            '/img/icon-files/DOCX.png' => 'docx',
            '/img/icon-files/DOS.png' => 'dos',
            '/img/icon-files/DVD.png' => 'dvd',
            '/img/icon-files/DWG.png' => 'dwg',
            '/img/icon-files/DWT.png' => 'dwt',
            '/img/icon-files/EMF.png' => 'emf',
            '/img/icon-files/EXC.png' => 'exc',
            '/img/icon-files/FON.png' => 'fon',
            '/img/icon-files/GIF.png' => 'gif',
            '/img/icon-files/HLP.png' => 'hlp',
            '/img/icon-files/HTML.png' => 'html',
            '/img/icon-files/IFO.png' => 'ifo',
            '/img/icon-files/INF.png' => 'inf',
            '/img/icon-files/INI.png' => 'ini',
            '/img/icon-files/INS.png' => 'ins',
            '/img/icon-files/IP.png' => 'ip',
            '/img/icon-files/ISO.png' => 'iso',
            '/img/icon-files/ISP.png' => 'isp',
            '/img/icon-files/JAVA.png' => 'java',
            '/img/icon-files/JFIF.png' => 'jfif',
            '/img/icon-files/JPEG.png' => 'jpeg',
            '/img/icon-files/JPG.png' => 'jpg',
            '/img/icon-files/LOG.png' => 'log',
            '/img/icon-files/M4A.png' => 'm4a',
            '/img/icon-files/MID.png' => 'mid',
            '/img/icon-files/MMF.png' => 'mmf',
            '/img/icon-files/MMM.png' => 'mmm',
            '/img/icon-files/MOV.png' => 'mov',
            '/img/icon-files/MOVIE.png' => 'movie',
            '/img/icon-files/MP2.png' => 'mp2',
            '/img/icon-files/MP2V.png' => 'mp2v',
            '/img/icon-files/MP3.png' => 'mp3',
            '/img/icon-files/MP4.png' => 'mp4',
            '/img/icon-files/MPE.png' => 'mpe',
            '/img/icon-files/MPEG.png' => 'mpeg',
            '/img/icon-files/MPG.png' => 'mpg',
            '/img/icon-files/MPV2.png' => 'mpv2',
            '/img/icon-files/NFO.png' => 'nfo',
            '/img/icon-files/PDD.png' => 'pdd',
            '/img/icon-files/PDF.png' => 'pdf',
            '/img/icon-files/PHP.png' => 'php',
            '/img/icon-files/PNG.png' => 'png',
            '/img/icon-files/PPT.png' => 'ppt',
            '/img/icon-files/PPTX.png' => 'pptx',
            '/img/icon-files/preview.png' => 'preview',
            '/img/icon-files/PSD.png' => 'psd',
            '/img/icon-files/RAR.png' => 'rar',
            '/img/icon-files/REG.png' => 'reg',
            '/img/icon-files/RTF.png' => 'rtf',
            '/img/icon-files/SCP.png' => 'scp',
            '/img/icon-files/THEME.png' => 'theme',
            '/img/icon-files/TIF.png' => 'tif',
            '/img/icon-files/TIFF.png' => 'tiff',
            '/img/icon-files/TLB.png' => 'tlb',
            '/img/icon-files/TTF.png' => 'ttf',
            '/img/icon-files/TXT.png' => 'txt',
            '/img/icon-files/UIS.png' => 'uis',
            '/img/icon-files/URL.png' => 'url',
            '/img/icon-files/VBS.png' => 'vbs',
            '/img/icon-files/VCR.png' => 'vcr',
            '/img/icon-files/VOB.png' => 'vob',
            '/img/icon-files/WAV.png' => 'wav',
            '/img/icon-files/WBA.png' => 'wba',
            '/img/icon-files/WMA.png' => 'wma',
            '/img/icon-files/WMV.png' => 'wmv',
            '/img/icon-files/WPL.png' => 'wpl',
            '/img/icon-files/WRI.png' => 'wri',
            '/img/icon-files/WTX.png' => 'wtx',
            '/img/icon-files/xls.png' => 'xls',
            '/img/icon-files/XLSX.png' => 'xlsx',
            '/img/icon-files/XML.png' => 'xml',
            '/img/icon-files/XSL.png' => 'xsl',
            '/img/icon-files/ZAP.png' => 'zap',
            '/img/icon-files/ZIP.png' => 'zip',
        );

        return array_search($type, $fileTypesIcon);


    }

}